### ISSUE TITLE
SILENT is not working

### ISSUE THREAD

**Issue by sehraf** [i2p/libsam3#10]
I get this 
```
SENDING: STREAM FORWARD ID=KXe1O836ednEUg1eUJf-hHbVDZGSjWH9w3THvi4EJieN-1rlhrQKgUVmMb5R7 PORT=4458 HOST=127.0.0.1 SILENT=���j
```

Same goes for CONNECT, interestingly only the first call has corrupted data, everything following is just empty:
```
SENDING: STREAM CONNECT ID=KXe1O836ednEUg1eUJf-hHbVDZGSjWH9w3THvi4EJieN-1rlhrQKgUVmMb5R7 DESTINATION=1e3...A== SILENT=��
SENDING: STREAM CONNECT ID=KXe1O836ednEUg1eUJf-hHbVDZGSjWH9w3THvi4EJieN-1rlhrQKgUVmMb5R7 DESTINATION=3ns...AA== SILENT=
SENDING: STREAM CONNECT ID=KXe1O836ednEUg1eUJf-hHbVDZGSjWH9w3THvi4EJieN-1rlhrQKgUVmMb5R7 DESTINATION=XX...AA== SILENT=
SENDING: STREAM CONNECT ID=KXe1O836ednEUg1eUJf-hHbVDZGSjWH9w3THvi4EJieN-1rlhrQKgUVmMb5R7 DESTINATION=0J...AA== SILENT=
SENDING: STREAM CONNECT ID=KXe1O836ednEUg1eUJf-hHbVDZGSjWH9w3THvi4EJieN-1rlhrQKgUVmMb5R7 DESTINATION=o0...AAA SILENT=
```

**Comment by eyedeekay** [comment]
Thanks for the report. I think I see what I did wrong, I should be able to fix it very shortly.

**Comment by eyedeekay** [comment]
Fix is checked in, let me know that it works for you and I will close the issue :)

**Comment by sehraf** [comment]
Can confirm that the string is now sound. 
Sadly another problem arose: it's sending `SILENT=false` for a silent session :weary:

**Comment by sehraf** [comment]
The `silent` variable gets set correctly.

**Comment by eyedeekay** [comment]
Oh jeez. Sorry about that. Thanks for letting me know, it should be fixed in a few minutes.

**Comment by eyedeekay** [comment]
@sehraf merged, please test when you can.

**Comment by sehraf** [comment]
`SENDING: STREAM FORWARD ID=mh...Kb PORT=4458 HOST=127.0.0.1 SILENT=true` :rocket: 
Incoming connections are working again, thanks alot!

**Comment by sehraf** [comment]
CONNECT is now broken, the code expects ans answer
```c
    if (!sam3IsGoodReply(rep, "STREAM", "STATUS", "RESULT", "OK")) {
```

**Comment by eyedeekay** [comment]
Should be fixed now.

**Comment by sehraf** [comment]
https://github.com/i2p/libsam3/commit/749519ab1f5ecf65cb9b74f97f0a08f306a05d42#r44499823

**Comment by eyedeekay** [comment]
Oh right. Good catch, fixed now.

**Comment by eyedeekay** [comment]
@sehraf any more issues with SILENT?

**Comment by sehraf** [comment]
nope, looks stable/fine to me.

**Comment by eyedeekay** [comment]
Thanks
